# -*- coding: utf-8 -*-
"""Iteration 1: Rocket Airbrake Deployment Flight Sim

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hh_nObZZUYChqqM_U0RYhcd0SHWCE7yX
"""

import numpy as np
import matplotlib.pyplot as plt

# Constants
g = 9.81               # gravity (m/s²)
rho = 1.06             # estimated air density (kg/m³)
Cd = 0.68              # drag coef
m = 0.595              # rocket mass (kg)
A_base = 0.00452369    # min drag area (m²) — rocket body
A_max = 0.00524229     # max drag area (m²) — with brakes fully deployed
target_apogee = 228.6  # meters

# Initial conditions
t = 0                  # reset time at burnout
h0 = 76.02             # initial height (m)
v0 = 69.95             # initial upward velocity (m/s)

dt = 0.01                              # timestep (s)
deploy_alts = np.arange(100, 224, 5)
results = []
print(deploy_alts)

def simulate(deploy_altitude):
    h = h0
    v = v0
    t = 0
    while v > 0:
        A = A_base if h < deploy_altitude else A_max
        F_d = 0.5 * rho * Cd * A * v**2
        a = -g - F_d / m
        v += a * dt
        h += v * dt
        t += dt
        # Prevent unrealistic heights
        if h < 0:
            break

    return h  # final apogee

for alt in deploy_alts:
    apogee = simulate(alt)
    results.append((alt, apogee))
print(results)

alts, apogees = zip(*results)
plt.figure(figsize=(10,5))
plt.plot(alts, apogees, label='Simulated Apogee')
plt.axhline(y=target_apogee, color='r', linestyle='--', label='Target Apogee (228.6m)')
plt.xlabel('Deployment Altitude (m)')
plt.ylabel('Resulting Apogee (m)')
plt.title('Optimal Deployment Altitude vs Final Apogee')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()